In [8]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [28]:
my_arr[1:10]
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
my_list[1:10]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
%time for i in range(10):my_arr2 = my_arr*i

Wall time: 26.9 ms


In [24]:
%time for i in range(10):my_list2 = my_list*i

Wall time: 469 ms


In [29]:
np.random.rand()

0.9696193301467583

In [30]:
np.random.rand(2)

array([0.0861759 , 0.06875838])

In [55]:
a = np.random.rand(5,5)
a

array([[0.13759073, 0.30459612, 0.50768092, 0.95409136, 0.1125322 ],
       [0.58230827, 0.94227697, 0.20127118, 0.82408154, 0.52647163],
       [0.84342391, 0.93655916, 0.97702991, 0.15908249, 0.94757259],
       [0.57583917, 0.85766714, 0.80540308, 0.04960591, 0.23831676],
       [0.83050295, 0.71660237, 0.53065876, 0.25539414, 0.31650867]])

In [56]:
a*10

array([[1.3759073 , 3.04596118, 5.07680925, 9.54091358, 1.12532198],
       [5.82308265, 9.42276968, 2.01271181, 8.24081536, 5.2647163 ],
       [8.4342391 , 9.36559157, 9.77029907, 1.59082493, 9.4757259 ],
       [5.75839172, 8.57667137, 8.05403083, 0.49605908, 2.3831676 ],
       [8.3050295 , 7.16602373, 5.30658759, 2.55394136, 3.16508672]])

In [57]:
a.shape

(5, 5)

In [58]:
a.dtype

dtype('float64')

In [60]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
d = [(1,2,3.5),(2,3,4),[4,6,7]]
a = np.array(d)

In [85]:
a

array([1, 2, 3])

In [79]:
a.ndim

3

In [82]:
a = np.array([1,2,3],dtype=np.int32)

In [84]:
a.dtype

dtype('int32')

In [89]:
a = a.astype(np.float64)

In [90]:
a.dtype

dtype('float64')

In [101]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [102]:
print(a,b)

[1 2 3 4] [5 6 7 8]


In [103]:
a>b

array([False, False, False, False])

In [104]:
a == b

array([False, False, False, False])

In [105]:
a*b

array([ 5, 12, 21, 32])

In [113]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [114]:
arr_slice = arr[5:8].copy()
arr_slice

array([6, 7, 8])

In [115]:
arr_slice[:] = 1

In [116]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
arr2d = np.array([[1,2,7,8,9],[3,4,0,1,2],[5,6,3,4,5]])

In [143]:
arr2d[:,:1]

array([[1],
       [3],
       [5]])

In [124]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [132]:
arr3d[1][1][2]

12

In [160]:
arr = np.array(["a","b","c","d","e","f"])
arr2 = np.random.randn(6,4)
arr2

array([[-0.28146003, -0.92943127, -0.66960954, -0.78293561],
       [-1.62592687, -0.48709945,  0.78114866,  0.41905857],
       [ 0.97260813, -0.41280246, -2.57227059,  1.68964575],
       [-1.6560457 ,  2.2018063 , -1.05362325, -0.25714888],
       [ 0.66797145,  0.82815112,  0.95039663,  0.32700292],
       [ 0.43440991, -0.18897696,  3.44714211,  0.85463585]])

In [150]:
arr2[arr == "a"]

array([[ 1.55460429,  1.43429151,  0.16940021, -0.6015346 ]])

In [165]:
arr2[:,arr[:4] !="a"]

array([[-0.92943127, -0.66960954, -0.78293561],
       [-0.48709945,  0.78114866,  0.41905857],
       [-0.41280246, -2.57227059,  1.68964575],
       [ 2.2018063 , -1.05362325, -0.25714888],
       [ 0.82815112,  0.95039663,  0.32700292],
       [-0.18897696,  3.44714211,  0.85463585]])

In [167]:
mask = (arr=="a") | (arr=="b")

In [168]:
mask

array([ True,  True, False, False, False, False])

In [169]:
arr2[mask]

array([[-0.28146003, -0.92943127, -0.66960954, -0.78293561],
       [-1.62592687, -0.48709945,  0.78114866,  0.41905857]])

In [183]:
arr = np.random.randint(0,25,(8,5))
arr

array([[10,  3, 19,  4, 24],
       [ 0, 20, 11, 12,  9],
       [19, 21, 11,  3, 23],
       [23,  1, 18,  4, 14],
       [24,  6,  7, 19, 13],
       [11, 23,  7,  3, 21],
       [ 3,  5, 15,  8, 12],
       [ 4, 15, 13, 22, 15]])

In [188]:
arr[[5,2,7,1]][:,[4,1,3,2]]

array([[21, 23,  3,  7],
       [23, 21,  3, 11],
       [15, 15, 22, 13],
       [ 9, 20, 12, 11]])

In [190]:
np.dot(arr.T,arr)

array([[1712,  924, 1155,  790, 1638],
       [ 924, 1666,  999,  872, 1595],
       [1155,  999, 1419,  873, 1673],
       [ 790,  872,  873, 1103, 1065],
       [1638, 1595, 1673, 1065, 2361]])

In [195]:
arr.swapaxes(1,0)

array([[10,  0, 19, 23, 24, 11,  3,  4],
       [ 3, 20, 21,  1,  6, 23,  5, 15],
       [19, 11, 11, 18,  7,  7, 15, 13],
       [ 4, 12,  3,  4, 19,  3,  8, 22],
       [24,  9, 23, 14, 13, 21, 12, 15]])

In [211]:
a = np.array([-3.2623, -6.0915, -6.663 ,  5.3731,  3.6182,  3.45  ,  5.0077])
b = np.array([1,2,3,4,5,6,7])

In [208]:
r,w = np.modf(a)
w

array([-3., -6., -6.,  5.,  3.,  3.,  5.])

In [209]:
r

array([-0.2623, -0.0915, -0.663 ,  0.3731,  0.6182,  0.45  ,  0.0077])

In [214]:
np.sqrt(a)

array([       nan,        nan,        nan, 1.52249625, 1.37918696,
       1.36287107, 1.49592416])

In [215]:
points = np.arange(-5, 5, 0.01)

In [216]:
 xs, ys = np.meshgrid(points, points)

In [217]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [218]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [235]:
arr = np.random.randint(0,25,(10,5))
a = np.random.randint(0,25,10)

In [231]:
arr

array([[19,  9, 16,  6,  1],
       [16, 18,  2,  4, 15],
       [22,  7, 22, 23,  7],
       [ 0, 22,  0, 22, 22],
       [ 0, 16, 18, 22, 15],
       [16,  4, 21,  2, 17],
       [14, 24, 10, 23,  1],
       [ 8,  6,  6,  6, 13],
       [ 8,  9, 18,  8, 22],
       [ 0,  5,  4,  7, 21]])

In [234]:
arr.cumsum(axis = 0)

array([[ 19,   9,  16,   6,   1],
       [ 35,  27,  18,  10,  16],
       [ 57,  34,  40,  33,  23],
       [ 57,  56,  40,  55,  45],
       [ 57,  72,  58,  77,  60],
       [ 73,  76,  79,  79,  77],
       [ 87, 100,  89, 102,  78],
       [ 95, 106,  95, 108,  91],
       [103, 115, 113, 116, 113],
       [103, 120, 117, 123, 134]], dtype=int32)

In [239]:
print(a)
a.cumsum(axis=0)

[ 5 20 16 15  6 22  4 21 12 24]


array([  5,  25,  41,  56,  62,  84,  88, 109, 121, 145], dtype=int32)